## YAML Template.
version: "3"

services:
    web:
        image: nginx:latest
        container_name: "snippets-nginx"
        ports:
            - "80:80"
        volumes:
            - .:/code
            - ./site.conf:/etc/nginx/conf.d/default.conf
            - ./var/log/nginx:/var/log/nginx
        links:
            - php
        logging:
            options:
                max-size: 50m
    php:
        image: php_image:latest
        container_name: "snippets-php-fpm"
        volumes:
            - .:/code
        logging:
            options:
                max-size: 50m
  
    db:
        build: ./db
        container_name: "snippets-db"
        volumes:
            - db-data:/var/lib/mysql
        restart: 'always'
        expose:
            - '3309'
        environment:
            - MYSQL_ROOT_PASSWORD=myrootpwdinsecure
        ports:
            - "3309:3306"
        logging:
            options:
                max-size: 50m
            
    cli:
        build:
            context: ./
            dockerfile: ./cli.docker
        volumes:
            - ./:/code
            - /var/www/data/snippets:/var/www/data/snippets
        environment:
            - DATABASE_URL=mysql://snippets-user:snippets-pwd@172.17.0.1:3309/snippets
            - SOLR_HOST=*.*.*.*
        logging:
            options:
                max-size: 50m
    
volumes:
    db-data:

 
  
